import type { Metadata } from "next";
import localFont from "next/font/local";
// import { Inter } from "next/font/google";

import "./globals.css";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

// const inter = Inter({
// 	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
// 	subsets: ["latin", "cyrillic"],
// });

export const metadata: Metadata = {
	title: "Экос - технологические решения",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistMono.variable} ${geistSans.variable} antialiased overflow-x-hidden`}>
				{children}
			</body>
		</html>
	);
}
